CREATE TABLE user (
	id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(30) NOT NULL,
    pwd VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE common_user (
	user_id BIGINT(20) NOT NULL PRIMARY KEY,
    cpf VARCHAR(20) NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE shopkeeper (
	user_id BIGINT(20) NOT NULL PRIMARY KEY,
    cnpj VARCHAR(20) NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE wallet (
	id BIGINT(20) NOT NULL PRIMARY KEY,
    balance DECIMAL (10, 2)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `transaction` (
	id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    payer_id BIGINT(20) NOT NULL,
    payee_id BIGINT(20) NOT NULL,
    amount DECIMAL (10, 2) NOT NULL,
    date datetime NOT NULL,
    CONSTRAINT fk_payer FOREIGN KEY (payer_id) REFERENCES user(id),
    CONSTRAINT fk_payee FOREIGN KEY (payee_id) REFERENCES user(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
